name: Test and deploy

on:
  push:
    branches:
      - main
      - deploy
      - ci

  workflow_dispatch:

jobs:
  test-project:
    name: Test project and report coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Test with coverage
        run: npm run coverage

  build-and-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: test-project
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: setup git
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git config --global user.name "Mukesh Gurpude"
          git config --global user.email "mukeshgurpude02@gmail.com"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: npm run build
      - name: Deploy
        run: npm run deploy
